import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Worker from '@/components/Worker'
import { Client, Server } from 'react-hydration-provider'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Server>
      <Head  >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      </Server>
      <Client>
      <main className='homePage'>
      <Worker />
       
      </main>
      </Client>
    </>
  )
}
